config/routes.rb
Rails.application.routes.draw do

  resources :cheeses
  resources :users

  get    '/favorites', to: 'favorites#index', as: 'new_favorite'
  post   '/favorite', to: 'favorites#create', as: 'favorite'
  delete '/unfavorite', to: 'favorites#destroy', as: 'unfavorite'

  get    '/login',  to: 'sessions#new',     as: 'new_login'
  post   '/login',  to: 'sessions#create',  as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

root 'cheeses#index'
end

app/models/cheese.rb
class Cheese < ActiveRecord::Base
  has_many :users, through: :favorites
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :cheese
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cheeses, through: :favorites
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user
  # Run 'current_user' before every controller action

  def authenticate_user
    unless user_logged_in?
      redirect_to new_login_path
    end
  end

  def current_user
    if user_logged_in?
      User.find(session[:logged_in_users_id])
    end
  end

  def user_logged_in?
    session[:logged_in_users_id].present?
  end
  helper_method :user_logged_in?
end

app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController
  before_action :set_cheese, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user, except: [:index, :show]
  # GET /cheeses
  # GET /cheeses.json
  def index
    @cheeses = Cheese.all
  end

  # GET /cheeses/1
  # GET /cheeses/1.json
  def show
  end

  # GET /cheeses/new
  def new
    @cheese = Cheese.new
  end

  # GET /cheeses/1/edit
  def edit
  end

  # POST /cheeses
  # POST /cheeses.json
  def create
    @cheese = Cheese.new(cheese_params)

    respond_to do |format|
      if @cheese.save
        format.html { redirect_to @cheese, notice: 'Cheese was successfully created.' }
        format.json { render :show, status: :created, location: @cheese }
      else
        format.html { render :new }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cheeses/1
  # PATCH/PUT /cheeses/1.json
  def update
    respond_to do |format|
      if @cheese.update(cheese_params)
        format.html { redirect_to @cheese, notice: 'Cheese was successfully updated.' }
        format.json { render :show, status: :ok, location: @cheese }
      else
        format.html { render :edit }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cheeses/1
  # DELETE /cheeses/1.json
  def destroy
    @cheese.destroy
    respond_to do |format|
      format.html { redirect_to cheeses_url, notice: 'Cheese was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cheese
      @cheese = Cheese.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cheese_params
      params.require(:cheese).permit(:name)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user, except: [:index]
  def index
    @favorites = Favorite.all
  end

  def create
    @Favorite = Favorite.new(favorite_params)
    @Favorite.user_id = current_user.id


    if @Favorite.save
      respond_to do |f|
        f.html do
          redirect_to :back
        end
        f.json do
          render json: @Favorite.to_json
        end
      end
    else
      flash[:alert] = 'Errors'
      render :back
    end
  end

  private

  def set_favorite
    @favorite = Favorite.find(params[:id])
  end

  def favorite_params
    params.require(:favorite).permit(:user_id, :cheese_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate_user

  def new #login page
  end

  def create #create the login session
    #username and password
    user = User.find_by_name(params[:name])
    if user.present? && user.authenticate(params[:password])
      set_user_session(user)
      redirect_to root_path, notice: "Successfully logged in!"
    else
      flash[:alert] = 'Name or Password did not match.'
      render :new
    end
  end

  def destroy #delete the login session
    session[:logged_in_users_id] = nil
    redirect_to root_path, notice: "Successfully logged out."
  end

  private

  def set_user_session(user)
    session[:logged_in_users_id] = user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user, only: [:show, :new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheeses_helper.rb
module CheesesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cheeses/_form.html.erb
<%= form_for(@cheese) do |f| %>
  <% if @cheese.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cheese.errors.count, "error") %> prohibited this cheese from being saved:</h2>

      <ul>
      <% @cheese.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cheeses/edit.html.erb
<h1>Editing Cheese</h1>

<%= render 'form' %>

<%= link_to 'Show', @cheese %> |
<%= link_to 'Back', cheeses_path %>

app/views/cheeses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cheeses</h1>

  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <div class="btn-group" role="group" aria-label="...">
    <tbody>
      <% @cheeses.each do |cheese| %>
        <tr>
          <td><%= cheese.name %></td>
          <td><%= link_to 'Show', cheese, class: 'btn btn-default btn-xs' %></td>
          <td><%= link_to "Mark Favorite", favorite_path(:favorite => { :cheese_id => cheese }), :method => :post, class: 'btn btn-default btn-xs' %></td>
        </tr>
      <% end %>
    </tbody>
    </div>
  </table>

app/views/cheeses/new.html.erb
<h1>New Cheese</h1>

<%= render 'form' %>

<%= link_to 'Back', cheeses_path %>

app/views/cheeses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cheese.name %>
</p>

<%= link_to 'Edit', edit_cheese_path(@cheese) %> |
<%= link_to 'Back', cheeses_path %>

app/views/favorites/delete.html.erb
<h1>Favorites#delete</h1>
<p>Find me in app/views/favorites/delete.html.erb</p>

app/views/favorites/index.html.erb
<h1>Listing Favorites</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Users</th>
      <th>Cheeses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user.name%></td>
        <td><%= favorite.cheese.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cheese', new_cheese_path, class: 'btn btn-default btn-xs' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheeseBlock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/united/bootstrap.min.css" rel="stylesheet" integrity="sha256-nKQVXFJ5JtDJlI5p1UcSf0JOFudCj9RgjBDsJSZPsS4= sha512-dbadXecsBCgqQ5XGx6SG+bO4vsfzznX6/NfAG4CuzLi76wcdLGAw2KIcsLyv7H5XsEGq0zaznpxDCAEIX9pdYA==" crossorigin="anonymous"></head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Cheeseums</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/cheeses">Cheeses</a></li>
        <li><a href="/favorites">Favorites </a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("logout", logout_path, method: :DELETE,  class: 'btn btn-info btn-xs') if user_logged_in?  %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class='container-fluid'>
  <div class="row">
        <div class="col-md-2"></div>
        <div class="well col-md-8">
            <%= yield %>
        </div>
        <div class="col-md-2"></div>
  </div>
</div>


<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.created_at%></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>